### ISSUE TITLE
this is a greate tool but it cannot take the hint() into account?

### ISSUE THREAD

**Issue by braindevices** [mongodb-labs/pymongoexplain#44] opened 2021-07-11 22:04 UTC
in mongo shell we can do `collection.explain().find().hint()` but it seems like this too cannot do that?

**Comment by braindevices** [comment] 2021-07-11 22:06
ah I get it use `hint=`

**Comment by ShaneHarvey** [comment] 2021-07-12 18:32
Thanks for filing this issue! Yes this is a bug and it should be fixed by https://github.com/mongodb-labs/pymongoexplain/issues/37. For now you'll need to pass all the cursor options as keyword arguments to the collection.find() call. For example:
```
collection.find({}, skip=4, limit=2, hint='x_1')
```

**Comment by agolin95** [comment] 2021-07-16 17:23
Closing as a duplicate of #37

**Closed** 2021-07-16 17:23 UTC
